### ISSUE TITLE
Präsentation responsive machen

### ISSUE THREAD

**Issue by EliasSchriefer** [EliasSchriefer/js-presentation#1]
style.css:

```CSS
html, body {
	margin: 0;
	padding: 0;
	height: 100vh;
	width: 100vw;
}

.slide {
	width: 100vw;
	height: 56.25vw;
	margin: 21.875vw 0;
}
```
